### ISSUE TITLE
Won't launch on OSX because it tries to start the UI on the wrong thread

### ISSUE THREAD

**Issue by mjc** [davy/pirate_game#2]
Looks like cocoa requires the UI to be started on the main thread.

```
Gaige:pirate_game mjc$ pirate_game 
***WARNING: Display must be created on main thread due to Cocoa restrictions.
LoadError: Couldn't load backend Shoes::Swt'. Error: load error: shoes/swt -- org.eclipse.swt.SWTException: Invalid thread access
org/jruby/RubyKernel.java:1082:in `require'
/Users/mjc/.rubies/jruby-1.7.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/mjc/.rubies/jruby-1.7.6/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
/Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes.rb:46:in `load_backend'
/Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/configuration.rb:10:in `backend'
/Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/app.rb:41:in `initialize'
/Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/app.rb:15:in `app'
/Users/mjc/.gem/jruby/1.9.3/gems/pirate_game-0.0.1/lib/pirate_game/client_app.rb:4:in `run'
/Users/mjc/.gem/jruby/1.9.3/gems/pirate_game-0.0.1/bin/pirate_game:5:in `(root)'
org/jruby/RubyKernel.java:1101:in `load'
/Users/mjc/.gem/jruby/1.9.3/bin/pirate_game:23:in `(root)'
  load_backend at /Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes.rb:49
       backend at /Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/configuration.rb:10
    initialize at /Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/app.rb:41
           app at /Users/mjc/.gem/jruby/1.9.3/gems/shoes-4.0.0.pre1/lib/shoes/app.rb:15
           run at /Users/mjc/.gem/jruby/1.9.3/gems/pirate_game-0.0.1/lib/pirate_game/client_app.rb:4
        (root) at /Users/mjc/.gem/jruby/1.9.3/gems/pirate_game-0.0.1/bin/pirate_game:5
          load at org/jruby/RubyKernel.java:1101
        (root) at /Users/mjc/.gem/jruby/1.9.3/bin/pirate_game:23
```

**Comment by tenderlove** [comment]
I got this too. :'(

**Comment by mjc** [comment]
https://gist.github.com/davy/f170c3d565e22f84b303#comment-947179 seems to work.

**Comment by tenderlove** [comment]
I got it to work.  It turned out I had the alias wrong. :(

**Comment by drbrain** [comment]
@mjc yep.

The shoes executable in the gem's bin directory is a shell script that sets up jruby properly. At present, there doesn't appear to be a way to use shoes4 to launch apps from a gem.

**Comment by drbrain** [comment]
Can someone check my instruction improvement?

**Comment by eval** [comment]
@drbrain only works when cwd equals the shoes checkout folder. Else I get:

``` bash
19:59:24 ~/src
$ /Users/gert/.rbenv/versions/jruby-1.7.4/gemsets/shoes/gems/shoes-4.0.0.pre1/bin/shoes ~/src/pirate_game/bin/pirate_game
LoadError: no such file to load -- shoes/cli
  require at org/jruby/RubyKernel.java:1054
  require at /Users/gert/.rbenv/versions/jruby-1.7.4/lib/ruby/shared/rubygems/custom_require.rb:36
```

With the shoes- and pirate_game-libs added to `RUBYLIB`, stuff works:

``` bash
20:01:27 ~/src
$ RUBYLIB=~/src/shoes4/lib:~/src/pirate_game/lib /Users/gert/.rbenv/versions/jruby-1.7.4/gemsets/shoes/gems/shoes-4.0.0.pre1/bin/shoes ~/src/pirate_game/bin/pirate_game
```
