### ISSUE TITLE
TypeError: no implicit conversion... registration and expiration logging disabled

### ISSUE THREAD

**Issue by MichaelDimmitt** [davy/pirate_game#8]
### Wanted to check out the pirate game! But, could not get it working. 

rvm list
### rvm rubies

<pre>
   jruby-9.1.10.0 [ x86_64 ]
=> jruby-9.1.7.0 [ x86_64 ]
   jruby-9.1.8.0 [ x86_64 ]
   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.3.3 [ x86_64 ]
   ruby-2.3.4 [ x86_64 ]
 * ruby-2.4.0 [ x86_64 ]
   ruby-2.4.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
</pre>

### Instructions that I followed: 
$ git clone http://github.com/shoes/shoes4
(additional) $ cd shoes4
$ git checkout 7d0a1eefea601917dd01419b14ded2812d0acb9f
$ gem build shoes.gemspec
$ gem install shoes-4.0.0.pre1.gem
$ alias shoes4='/path/to/gems/shoes-4.0.0.pre1/bin/shoes'
$ gem install pirate_game

$ ring_server

### Command:
dir: ~/shoes4
$ ring_server
### Output:
registration and expiration logging disabled
TypeError: no implicit conversion of Fixnum into String
                  udp at org/jruby/ext/socket/Addrinfo.java:337
          make_socket at /Users/michaeldimmitt/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/rinda/ring.rb:134
  block in initialize at /Users/michaeldimmitt/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/rinda/ring.rb:110
                 each at org/jruby/RubyArray.java:1733
           initialize at /Users/michaeldimmitt/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/rinda/ring.rb:106
                  run at /Users/michaeldimmitt/.rvm/gems/jruby-9.1.7.0/gems/RingyDingy-1.6/lib/ringy_dingy/ring_server.rb:290
                  run at /Users/michaeldimmitt/.rvm/gems/jruby-9.1.7.0/gems/RingyDingy-1.6/lib/ringy_dingy/ring_server.rb:191
               <main> at /Users/michaeldimmitt/.rvm/gems/jruby-9.1.7.0/gems/RingyDingy-1.6/bin/ring_server:6
                 load at org/jruby/RubyKernel.java:979
               <eval> at /Users/michaeldimmitt/.rvm/gems/jruby-9.1.7.0/bin/ring_server:1
                 eval at org/jruby/RubyKernel.java:1000
               <main> at /Users/michaeldimmitt/.rvm/gems/jruby-9.1.7.0/bin/jruby_executable_hooks:15
Exception in thread "Ruby-0-Thread-1: /Users/michaeldimmitt/.rvm/rubies/jruby-9.1.7.0/lib/ruby/stdlib/drb/drb.rb:1539" java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68)
	at org.jruby.util.io.SelectorPool.put(SelectorPool.java:88)
	at org.jruby.util.io.SelectExecutor.selectEnd(SelectExecutor.java:59)
	at org.jruby.util.io.SelectExecutor.go(SelectExecutor.java:44)
	at org.jruby.RubyIO.select(RubyIO.java:3390)
	at org.jruby.RubyIO$INVOKER$s$0$3$select.call(RubyIO$INVOKER$s$0$3$select.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:720)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)

**Comment by MichaelDimmitt** [comment]
dir: ~/shoes4
### Second Command:
shoes4 bin/game_master
### Output:
-bash: /path/to/gems/shoes-4.0.0.pre1/bin/shoes: No such file or directory
